#!/bin/bash
### BEGIN INIT INFO
# Provides:          check_for_key
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: checks for USB KEY in lock
# Description:       This file is part of the package USB-Lock-Key,
#		     its purpose is to check for when the key is inserted
### END INIT INFO

# Author: Kyle Frizzell <kdfrizale on GitHub>


##Variable file is the location of the mount point of the thumb drive with the key-file on it
##the contents DO NOT matter, but the name of the file must be exact
file="/mnt/usbkey/key_1.passkey"

while true
do
	if [ -f "$file" ]
	then
		echo "$file found."
		#This will execute when the key is inserted
		#add any code you want within this then statement
		#below is an example of what I used
		#python /home/pi/gpio_on.py
		
	else
		echo "$file not found."
		#This will execute when the key is removed
		#add any code you want within this then statement
		#below is an example of what I used
		#python /home/pi/gpio_off.py
		
	fi
	sleep 4 #Sleep an arbitrary number of seconds in order to not consume all the CPU cylces
done &

